config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'member/sessions'
  }
  
  authenticated :member do

    resources :class_instructors
    root 'dashboard#index'

    get '/example', to: 'dashboard#example', as: 'dashboard_example'

    get '/planos_dos_alunos', to: 'student_plans#index', as: :student_plans
    post '/planos_dos_alunos', to: 'student_plans#create'
    scope 'aluno/:person_id/plano' do
      get '/novo', to: 'student_plans#new', as: :new_student_plan
      get '/editar', to: 'student_plans#edit', as: :edit_student_plan
      get '/', to: 'student_plans#show', as: :student_plan
      patch '/', to: 'student_plans#update'
      put '/', to: 'student_plans#update'
      delete '/', to: 'student_plans#destroy'
    end

    get '/faixas', to: 'belts#index', as: :belts
    post '/faixas', to: 'belts#create'
    scope 'aluno/:person_id/faixa' do
      get '/nova', to: 'belts#new', as: :new_belt
      get ':id/editar', to: 'belts#edit', as: :edit_belt
      get '/', to: 'belts#show', as: :belt
      get '/:id/mudar_faixa', to: 'belts#change_belt', as: :change_belt
    end

    scope 'aluno/:id/faixa' do
      patch '/', to: 'belts#update'
      put '/', to: 'belts#update'
      delete '/', to: 'belts#destroy'
    end

    scope 'financeiro' do
      get '/', to: 'dashboard#financial_index', as: :financial_index
      post '/novo_pagamento/:id/', to: 'payments#new_student_payment', as: 'new_student_payment'
      post '/receber_pagamento/:id/', to: 'payments#recive_payment', as: 'recive_payment'
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :tuition_fees, path: 'mensalidades'
        resources :rents, path: 'alugueis'
        resources :discounts, path: 'pacotes'
        resources :payments, path: 'pagamentos'
      end
    end

    scope 'administrativo' do
      get '/', to: 'dashboard#administrative_index', as: :administrative_index
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :pakua_classes, path: 'aulas'
      end
    end

    scope(path_names: { new: 'novo', edit: 'editar' }) do
      resources :people, path: 'membros'
    end

    get 'instrutores', to: 'instructors#index'
    get 'instrutores/novo', to: 'instructors#new'
    get 'instrutores/:id', to: 'instructors#show'
    get 'instrutores/:id/editar', to: 'instructors#edit'
    get 'instrutores', to: 'instructors#create'
    get 'instrutores/:id', to: 'instructors#update'
    get 'instrutores/:id', to: 'instructors#destroy'
    get 'alunos', to: 'students#index'
    get 'alunos/novo', to: 'students#new'
    get 'alunos/:id', to: 'students#show'
    get 'alunos/:id/editar', to: 'students#edit'
    get 'alunos', to: 'students#create'
    get 'alunos/:id', to: 'students#update'
    get 'alunos/:id', to: 'students#destroy'
    get 'membros/:id/informacao', to: 'people#edit_information', as: 'edit_information'
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

  unauthenticated :member do
    get '/inscricao', to: 'people#new_student_form', as: 'new_student_form'
    post '/membros', to: 'people#create', as: 'create_new_student'
    get '/boas_vindas', to: 'dashboard#welcome', as: 'welcome'
    get '/cadastro_existente', to: 'dashboard#welcome_back', as: 'welcome_back'
  end

  authenticate :member do
    get '/', to: 'dashboard#index', as: 'not_logged_root'
  end
end

app/models/tuition_fee.rb
class TuitionFee < ApplicationRecord
  validates :weekly_classes, :fee, :validity, presence: true

  def weekly_class_text
    return "#{weekly_classes} aulas semanais" unless weekly_classes.zero?

    return 'Plano Livre' if weekly_classes.zero?

    'Plano Inválido'
  end
end

app/controllers/tuition_fees_controller.rb
class TuitionFeesController < ApplicationController
  before_action :set_tuition_fee, only: %i[ show edit update destroy ]

  # GET /tuition_fees or /tuition_fees.json
  def index
    current_tuition_fee_table
    @tuition_fees = TuitionFee.all - @current_tuition_fee
  end

  # GET /tuition_fees/1 or /tuition_fees/1.json
  def show
  end

  # GET /tuition_fees/new
  def new
    @tuition_fee = TuitionFee.new
  end

  # GET /tuition_fees/1/edit
  def edit
  end

  # POST /tuition_fees or /tuition_fees.json
  def create
    @tuition_fee = TuitionFee.new(tuition_fee_params)

    respond_to do |format|
      if @tuition_fee.save
        format.html { redirect_to tuition_fees_path, notice: 'O Plano foi criado' }
        format.json { render :show, status: :created, location: @tuition_fee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tuition_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuition_fees/1 or /tuition_fees/1.json
  def update
    respond_to do |format|
      if @tuition_fee.update(tuition_fee_params)
        format.html { redirect_to tuition_fees_path, notice: 'O Plano foi alterado com sucesso' }
        format.json { render :show, status: :ok, location: @tuition_fee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tuition_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuition_fees/1 or /tuition_fees/1.json
  def destroy
    @tuition_fee.destroy
    respond_to do |format|
      format.html { redirect_to tuition_fees_url, notice: "Tuition fee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuition_fee
      @tuition_fee = TuitionFee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tuition_fee_params
      params.require(:tuition_fee).permit(:weekly_classes, :fee, :validity)
    end
end

app/helpers/tuition_fees_helper.rb
module TuitionFeesHelper
end

app/views/tuition_fees/_form.html.erb
<section class="content">
  <div class="container-fluid">
    <%= form_with(model: tuition_fee, local: true) do |form| %>
      <% if tuition_fee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tuition_fee.errors.count, "error") %> prohibited this tuition_fee from being saved:</h2>

          <ul>
            <% tuition_fee.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Valor da Aula</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div class='form-group'>
                <h4 class="mb-0"><%= form.label :weekly_classes, 'Quantidade de Aulas Semanais', class: "mb-0" %></h4>
                <%= form.number_field :weekly_classes, class: "form-control form-control-border", min: 0 %>
                * Para o plano livre, selecione a quantidade de 0 aulas
              </div>

              <div class='form-group'>
                <h4 class="mb-0"><%= form.label :fee, 'Valor da Mensalidade', class: "mb-0" %></h4>
                <%= form.text_field :fee, class: "form-control form-control-border" %>
              </div>

              <div class='form-group'>
                <h4 class="mb-0"><%= form.label :validity, 'Válido à partir de', class: "mb-0" %></h4>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                  </div>
                  <input type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask="" id="tuition_fee_validity" name="tuition_fee[validity]" value="<%= @tuition_fee.validity.nil? ? date_to_string(Date.today) : date_to_string(@tuition_fee.validity) %>">
                </div>
              </div>

              <div class="actions">
                <%= form.submit 'Salvar', class: 'btn btn-primary'  %>
                <%= link_to 'Voltar para Administrativo', administrative_index_path, class: 'btn btn-secondary' %>
                <%= link_to 'Voltar para Valores de Aulas', tuition_fees_path, class: 'btn btn-secondary' %>
              </div>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tuition_fees/edit.html.erb
<%= render 'form', tuition_fee: @tuition_fee %>

<%= link_to 'Show', @tuition_fee %>

app/views/tuition_fees/index.html.erb
<%= sanitize page_title_with_button('Mensalidades', false) %>
<p id="notice"><%= notice %></p>

<section class="content">
  <% if TuitionFee.any? %>
    <%= generate_index_table({table_name: "Mensalidade Vigente (Desde #{date_format(@starting_date_for_current_fees)})", model: TuitionFee, objects: @current_tuition_fee, translated_names: ['Aulas semanais', 'Valor', 'Vigência'], new_label: 'Nova Mensalidade', crud_paths: true, translate_data: {'weekly_classes' => {'0' => 'Plano Livre'}} }).html_safe %>
  <% end %>
  <br><br>
  <%= generate_index_table({table_name: "Mensalidades Anteriores", model: TuitionFee, objects: @tuition_fees, translated_names: ['Aulas semanais', 'Valor', 'Vigência'], new_label: 'Nova Mensalidade', crud_paths: true, translate_data: {'weekly_classes' => {'0' => 'Plano Livre'}} }).html_safe %>
</section>

app/views/tuition_fees/new.html.erb
<%= render 'form', tuition_fee: @tuition_fee %>

app/views/tuition_fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weekly classes:</strong>
  <%= @tuition_fee.weekly_classes %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @tuition_fee.fee %>
</p>

<p>
  <strong>Validity:</strong>
  <%= @tuition_fee.validity %>
</p>

<%= link_to 'Edit', edit_tuition_fee_path(@tuition_fee) %> |
<%= link_to 'Back', tuition_fees_path %>