config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'member/sessions'
  }
  
  authenticated :member do

    resources :class_instructors
    root 'dashboard#index'

    get '/example', to: 'dashboard#example', as: 'dashboard_example'

    get '/planos_dos_alunos', to: 'student_plans#index', as: :student_plans
    post '/planos_dos_alunos', to: 'student_plans#create'
    scope 'aluno/:person_id/plano' do
      get '/novo', to: 'student_plans#new', as: :new_student_plan
      get '/editar', to: 'student_plans#edit', as: :edit_student_plan
      get '/', to: 'student_plans#show', as: :student_plan
      patch '/', to: 'student_plans#update'
      put '/', to: 'student_plans#update'
      delete '/', to: 'student_plans#destroy'
    end

    get '/faixas', to: 'belts#index', as: :belts
    post '/faixas', to: 'belts#create'
    scope 'aluno/:person_id/faixa' do
      get '/nova', to: 'belts#new', as: :new_belt
      get ':id/editar', to: 'belts#edit', as: :edit_belt
      get '/', to: 'belts#show', as: :belt
      get '/:id/mudar_faixa', to: 'belts#change_belt', as: :change_belt
    end

    scope 'aluno/:id/faixa' do
      patch '/', to: 'belts#update'
      put '/', to: 'belts#update'
      delete '/', to: 'belts#destroy'
    end

    scope 'financeiro' do
      get '/', to: 'dashboard#financial_index', as: :financial_index
      post '/novo_pagamento/:id/', to: 'payments#new_student_payment', as: 'new_student_payment'
      post '/receber_pagamento/:id/', to: 'payments#recive_payment', as: 'recive_payment'
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :tuition_fees, path: 'mensalidades'
        resources :rents, path: 'alugueis'
        resources :discounts, path: 'pacotes'
        resources :payments, path: 'pagamentos'
      end
    end

    scope 'administrativo' do
      get '/', to: 'dashboard#administrative_index', as: :administrative_index
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :pakua_classes, path: 'aulas'
      end
    end

    scope(path_names: { new: 'novo', edit: 'editar' }) do
      resources :people, path: 'membros'
    end

    get 'instrutores', to: 'instructors#index'
    get 'instrutores/novo', to: 'instructors#new'
    get 'instrutores/:id', to: 'instructors#show'
    get 'instrutores/:id/editar', to: 'instructors#edit'
    get 'instrutores', to: 'instructors#create'
    get 'instrutores/:id', to: 'instructors#update'
    get 'instrutores/:id', to: 'instructors#destroy'
    get 'alunos', to: 'students#index'
    get 'alunos/novo', to: 'students#new'
    get 'alunos/:id', to: 'students#show'
    get 'alunos/:id/editar', to: 'students#edit'
    get 'alunos', to: 'students#create'
    get 'alunos/:id', to: 'students#update'
    get 'alunos/:id', to: 'students#destroy'
    get 'membros/:id/informacao', to: 'people#edit_information', as: 'edit_information'
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

  unauthenticated :member do
    get '/inscricao', to: 'people#new_student_form', as: 'new_student_form'
    post '/membros', to: 'people#create', as: 'create_new_student'
    get '/boas_vindas', to: 'dashboard#welcome', as: 'welcome'
    get '/cadastro_existente', to: 'dashboard#welcome_back', as: 'welcome_back'
  end

  authenticate :member do
    get '/', to: 'dashboard#index', as: 'not_logged_root'
  end
end

app/models/person.rb
class Person < ApplicationRecord
  encrypts :name, :address, :cpf, :phone, :occupation, :other_option, :cep, :email
  encrypts :birthdate, :start_date, type: :date
  encrypts :school_level, :status, :civil_status, :marketing, type: :integer
  blind_index :birthdate, :start_date, :school_level, :status, :civil_status, :marketing, :email, :cpf

  validates :name_ciphertext, :birthdate_ciphertext, :cpf_ciphertext, :school_level_ciphertext,
  :occupation_ciphertext, :civil_status_ciphertext, :email_ciphertext, 
  :cep_ciphertext, :address_ciphertext, :phone_ciphertext, :start_date_ciphertext, presence: true

  before_save :check_marketing

  has_many :student_plans
  has_many :payments, through: :student_plans
  has_many :belts

  attribute :role, :integer, default: :student
  attribute :status, :integer, default: :not_checked

  scope :instructors, -> { where('role >= 3')}
  scope :instructors_of, -> (modality) { 
    where(role: ['instructor', 'student_and_instructor']).left_joins(:belts).where('belts.color > 4').where('belts.modality' => modality).uniq
  }

  enum role: {
    student: 1,
    open_class_student: 2,
    student_and_instructor: 3,
    instructor: 4
  }

  enum school_level: {
    ensino_fundamental: 1,
    ensino_medio: 2,
    ensino_superior: 3
  }

  enum civil_status: {
    solteiro: 1,
    casado: 2,
    viuvo: 3,
    divorciado: 4
  }

  enum status: {
    not_checked: 0,
    open_class: 1,
    active: 2,
    inactive: 3
  }

  enum marketing: {
    recommendation: 0,
    google: 1,
    facebook: 2,
    instagram: 3,
    flyer: 4,
    other: 5
  }

  def check_marketing
    if self.other_option.present?
      self.marketing = 'other'
    elsif self.other_option.blank? && self.marketing = 'other'
      self.marketing = nil
    end
  end

  def pakua_student?
    %w[student open_class_student].include?(self.role)
  end

  def pakua_instructor?
    %w[student_and_instructor instructor].include?(self.role)
  end

  def role_br
    if student?
      'Aluno(a)'
    elsif open_class_student?
      'Aluno(a) de aula Inaugural'
    elsif student_and_instructor?
      'Aluno(a) e Instrutor(a)'
    else
      'Instrutor(a)'
    end
  end

  def greatest_belt_color
    return '' if belts.blank?

    belts.select(:color).group(:color).order(:color).uniq.last.color
  end

  # student methods
  def latest_student_plan
    student_plans.order(:created_at).last
  end

  # instructor methods
  def can_be_instructor_of(modality)
    belts.where('5 <= color').where(modality: modality)
  end

  def can_be_instructor?
    belts.where('5 <= color').any?
  end

  def student_level_translation
    if self.ensino_fundamental
      'Ensino Fundamental'
    elsif self.ensino_medio
      'Ensino Médio'
    else
      'Ensino Superior'
    end
  end


end

app/controllers/people_controller.rb
# frozen_string_literal: true

# Manipulation of people data
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy edit_information]
  before_action :roles_data, only: %i[new edit update]
  before_action :payment_data, only: %i[show]
  before_action :belts_data, only: %i[show]

  layout :set_view_layout

  # GET /people or /people.json
  def index
    get_people_data
  end

  # GET /people/1 or /people/1.json
  def show
    @any_pakua_class = PakuaClass.first
  end

  # GET /people/new
  def new
    @person = Person.new
    @view_action = 'Novo Membro'
  end

  # GET /people/1/edit
  def edit
    @view_action = 'Editar Membro'
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    redirect_to welcome_back_path and return if Person.find_by(cpf: @person.cpf).present?
    
    if params["commit"] == 'Cadastrar'
      return_path = welcome_path
      error_path = :new_student_form
    elsif params[:information].blank? || params[:information].nil?
      return_path = people_path
      error_path = :new
    else
      return_path = person_path(@person)
      error_path = :new
    end
    respond_to do |format|
      if @person.save
        if params["modalities"].present?
          params["modalities"].keys.each do |m|
            Belt.create(person: @person, color: :branca, modality: m.to_sym, start_date: @person.start_date)
          end
        end
        format.html { redirect_to return_path, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        roles_data
        @modalities = params["modalities"].nil? ? [] : params["modalities"] 
        @view_action = 'Novo Membro'
        format.html { render error_path, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_path(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        roles_data
        @view_action = 'Editar Membro'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit_information
  end

  def new_student_form
    @person = Person.new
    @view_action = 'Novo Membro'
    @modalities = []
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:name, :address, :birthdate, :phone, :cpf, :role, :start_date,
      :information, :civil_status, :status, :email, :school_level, :occupation, :cep, :other_option,
      :marketing)
  end

  def roles_data
    @roles = { aluno: 1, aluno_de_aula_inaugural: 2, aluno_e_instrutor: 3, instrutor: 4, instrutor_intinerante: 5 }
  end

  def payment_data
    return unless @person.pakua_student?

    @today = Date.today
    #REFACTOR
    payments = @person.payments.where(':start_date <= due_date and due_date <= :end_date', {start_date: Date.new(@today.year, 1, 1), end_date: Date.new(@today.year, 12, 31)})
    @months_and_status = {  jan: { style: '' }, fev: { style: '' }, mar: { style: '' }, abr: { style: '' }, mai: { style: '' }, jun: { style: '' },
                            jul: { style: '' }, ago: { style: '' }, set: { style: '' }, out: { style: '' }, nov: { style: '' }, dez: { style: '' } }
    payments.each do |p|
      @payment = p if @today.month == p.due_date.month
      case p.due_date.month
      when 1
        @months_and_status[:jan] = { id: p.id, style: get_month_style(p) }
      when 2
        @months_and_status[:fev] = { id: p.id, style: get_month_style(p) }
      when 3
        @months_and_status[:mar] = { id: p.id, style: get_month_style(p) }
      when 4
        @months_and_status[:abr] = { id: p.id, style: get_month_style(p) }
      when 5
        @months_and_status[:mai] = { id: p.id, style: get_month_style(p) }
      when 6
        @months_and_status[:jun] = { id: p.id, style: get_month_style(p) }
      when 7
        @months_and_status[:jul] = { id: p.id, style: get_month_style(p) }
      when 8
        @months_and_status[:ago] = { id: p.id, style: get_month_style(p) }
      when 9
        @months_and_status[:set] = { id: p.id, style: get_month_style(p) }
      when 10
        @months_and_status[:out] = { id: p.id, style: get_month_style(p) }
      when 11
        @months_and_status[:nov] = { id: p.id, style: get_month_style(p) }
      else
        @months_and_status[:dez] = { id: p.id, style: get_month_style(p) }
      end
    end
  end

  def belts_data
    @belts = {  acrobacia: nil, armas_de_corte: nil, arqueria: nil,
                arte_marcial: nil, ritmo: nil, tai_chi_pa_kua: nil, yoga: nil}
    belts = @person.belts.order(color: :desc, modality: :asc, start_date: :desc)
    return unless belts.any?

    belts.each do |belt|
      @belts[belt.modality.to_sym] = belt if @belts[belt.modality.to_sym].nil?
    end
  end

  def get_month_style(payment)
    if payment.due_date.month == @today.month
      'bg-primary text-white'
    elsif payment.paid?
      'bg-success text-white'
    else
      'bg-danger text-white'
    end
  end

  def set_view_layout
    return 'application' if %w[new_student_form create].include?(action_name)

    'sb_admin2'
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_belts_information.html.erb
<div class="col-md-5">
          <!-- plan -->
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <h3 class="profile-username text-center">Faixas</h3>

              <ul class="list-group list-group-unbordered mb-3">
                <% if @belts.values.uniq.size == 1 && !@belts.values[0].nil? %>
                  <li class="list-group-item text-center">
                    <b>Nenhuma Faixa Cadastrada</b>
                  </li>  
                <% else %>
                  <% @belts.each do |k, belt| %>
                    <% unless belt.nil? %>
                      <li class="list-group-item">
                        <div class="row align-items-center">
                          <div class="col-3">
                            <b><%= modality_name(k.to_s) %></b>
                          </div>
                          <div class="col-3 text-center">
                            <span class="badge bg-primary" style="<%= belt_color_style(belt.color) %>"><%= belt.color.humanize.upcase %></span>
                          </div>
                          <div class="col-3">
                            <% unless belt.color == "preta_viii"%>
                              <a class="float-right"><%= link_to 'Mudar', change_belt_path(@person, belt), class: 'btn btn-success btn-block' %></a>
                            <% end %>
                          </div>
                          <div class="col-3">
                            <a class="float-right"><%= link_to 'Editar', edit_belt_path(@person, belt), class: 'btn btn-primary btn-block' %></a>
                          </div>
                        </div>
                      </li>
                    <% end %>
                  <% end %>
                <% end %>
              </ul>
              <% unless !@belts.values.include?(nil) %>
                <%= link_to "Adicionar Faixa ao #{pakua_title(@person).capitalize}", new_belt_path(@person), class: 'btn btn-primary btn-block' %>
              <% end %>

              <%# link_to 'Editar', edit_person_path(@person), class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </div>

app/views/people/_inactive.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- /.card -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Inativos
            </h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% if @inactive.blank? %>
                  <tr>
                    <td>
                      Ninguém nesta categoria
                    </td>
                  </tr>
                <% else %>
                  <% @inactive.each do |person| %>
                    <tr>
                      <td><%= person.name %></td>
                      <td><%= link_to 'Ver', person, class: "btn btn-info" %></td>
                      <td><%= link_to 'Editar', edit_person_path(person), class: "btn btn-warning"  %></td>
                      <td><%= link_to 'Excluir', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %></td>
                    </tr>
                  <% end %>
                <% end%>
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
</section>
<br>

app/views/people/_instructors.html.erb
<%= generate_index_table({table_name: 'Instrutores', model: Person, objects: @instructors, show_attributes: ['name', 'start_date'], translated_names: ['Nome', 'Início de Atividades'], new_label: 'Novo Instrutor', crud_paths: true }).html_safe %>

app/views/people/_months_payment.html.erb
<div class="col-md-4">

  <!-- Profile Image -->
  <div class="card card-primary card-outline">
    <div class="card-body box-profile">
      <h3 class="profile-username text-center">Pagamentos do Ano</h3>

      <p class="text-muted text-center"><b><%= @today.year %></b></p>
      <% @months_and_status.each do |month, status|%>
        <% if %w[jan abr jul out].include?(month.to_s)%>
          <div class="row">
        <% end %>
        <div class="col-4 month-slot text-center">
          <% if status.has_key?(:id) %>
            <%= link_to payment_path(status[:id]), class: "col-12 month #{status[:style]}", style: "display: block" do %>
              <%= month.to_s.upcase %>
            <% end %>
          <% else %>
            <div class="col-12 text-center month <%= status[:style] %>">
              <%= month.to_s.upcase %>
            </div>
          <% end %>
        </div>
        <% if %w[mar jun set dez].include?(month.to_s)%>
          </div>
        <% end %>
      <% end %>
      

    </div>
  </div>
</div>

<style>
  .month {
    padding: 5px 0;
    margin: 10px 0;
  }
</style>

app/views/people/_payments.html.erb
<div class="col-md-4">
  <!-- Profile Image -->
  <div class="card card-primary card-outline">
    <div class="card-body box-profile">
      <h3 class="profile-username text-center">Pagamentos</h3>

      <p class="text-muted text-center"><b><%= @payment.nil? ? br_month(Date.today.month) : br_month(@payment.due_date.month) %></b></p>

      <% if @payment.blank? %>
        <ul class="list-group list-group-unbordered mb-3">
          <li class="list-group-item">
            <b>Nenhum pagamento para o mês atual foi gerado</b>
            <br>
          </li>
        </ul>
        <%= button_to 'Gerar Novo Pagamento', new_student_payment_path(@person), class: 'btn btn-primary btn-block'%>
        <br>
      <% else %>
        <ul class="list-group list-group-unbordered mb-3">
          <li class="list-group-item">
            <b>Status</b><a class="float-right"><%= @payment.paid? ? 'Pago' : 'Em Aberto' %></a>
          </li>
          <li class="list-group-item">
            <b>Vencimento</b> <a class="float-right"><%= date_format(@payment.due_date) %></a>
          </li>
          <li class="list-group-item">
            <b>Valor</b> <a class="float-right"><%= to_money(@payment.student_plan.final_tuition_fee) %></a>
          </li>
          <% if !@payment.paid_fee.nil? && (@payment.paid_fee != @payment.payment_fee) %>
            <li class="list-group-item">
              <b>Valor Pago</b> <a class="float-right"><%= to_money(@payment.paid_fee) %></a>
            </li>
          <% end %>
        </ul>
        <% if @payment.paid_fee.nil? %>
          <%= button_to 'Receber Pagamento', recive_payment_path(@payment), class: 'btn btn-primary btn-block' %>
        <% elsif @payment.paid_fee.to_f < @payment.payment_fee.to_f %>
          <%= button_to 'Ajustar Pagamento', recive_payment_path(@payment), class: 'btn btn-primary btn-block' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/people/_people_data.html.erb
<div class="row">
  <%= generate_value_card('Membros', 'fa fa-users ', @people.count, nil, 'primary').html_safe %>
  <%= generate_value_card('Alunos', 'fa fa-user ', @students.count, nil, 'success').html_safe %>
  <%= generate_value_card('Instrutores', 'fa fa-user-graduate ', @instructors.count, nil, 'info').html_safe %>
</div>

app/views/people/_person_data.html.erb
<div class="col-md-4">

  <!-- Profile Image -->
  <div class="card card-primary card-outline">
    <div class="card-body box-profile">
      <div class="text-center">
        <img class="profile-user-img img-fluid img-circle"
              src="../../dist/img/user4-128x128.jpg"
              alt="User profile picture">
      </div>

      <h3 class="profile-username text-center"><%= @person.name %></h3>

      <p class="text-muted text-center"><b><%= @person.role_br+(@person.belts.any? ? " Faixa " + belt_color_name(@person.greatest_belt_color) : "" ) %></b></p>

      <ul class="list-group list-group-unbordered mb-3">
        <li class="list-group-item">
          <b>Endereço</b> <a class="float-right"><%= @person.address %></a>
        </li>
        <li class="list-group-item">
          <b>Nascimento</b><a class="float-right"><%= @person.birthdate.nil? ? 'Não informado' : date_format(@person.birthdate)%></a>
        </li>
        <li class="list-group-item">
          <b>Celular</b> <a class="float-right"><%= @person.phone %></a>
        </li>
        <li class="list-group-item">
          <b>CPF</b> <a class="float-right"><%= @person.cpf %></a>
        </li>
        <li class="list-group-item">
          <b>Início na Escola</b> <a class="float-right"><%= date_format(@person.start_date) %></a>
        </li>
      </ul>
      <% if !@person.information.blank? || !@person.information.nil? %>
        <div class="mb-3">
          <b>Informações</b> <a class="float-right"><%= @person.information %></a>
          <br>
        </div>
      <% end %>
      <%= link_to 'Editar', edit_person_path(@person), class: 'btn btn-primary btn-block' %>
      <%= link_to 'Editar Informações Extras', edit_information_path(@person), class: 'btn btn-success btn-block' %>
      <%= link_to 'Voltar', people_path, class: 'btn btn-secondary btn-block' %>
    </div>
    <!-- /.card-body -->
  </div>
</div>

app/views/people/_students.html.erb
<%= generate_index_table({table_name: 'Alunos', model: Person, objects: @students, show_attributes: ['name', 'start_date'],  translated_names: ['Nome', 'Início de Atividades'], new_label: 'Novo Aluno', crud_paths: true}).html_safe %>

app/views/people/edit.html.erb
<%= render 'form', person: @person %>

app/views/people/edit_information.html.erb
<section class="content">
  <div class="container-fluid">
    <%= form_with(model: @person, local: true) do |form| %>
      <% if @person.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

          <ul>
            <% @person.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><%= @view_action %></h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <h4 class="mb-0"><%= form.label :information, 'Informações', class: "mb-0" %></h4>
                <%= form.text_area :information, class: "form-control", rows: "5", style:"resize: none;" %>
              </div>

              <div class="actions">
                <%= form.submit 'Salvar', class: 'btn btn-primary' %>
                <%= link_to 'Voltar para Membros', people_path, class: 'btn btn-secondary' %>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/people/index.html.erb
<%= sanitize page_title_with_button('Membros', false) %>

<%= render 'people_data' %>

<p id="notice"><%= notice %></p>

<section class="content">
  <%= render 'students' %>
  <br><br><br>
  <%= render 'instructors' %>
  <br><br><br>
  <%# render 'inactive' %>
</section>

app/views/people/new_student_form.erb
<%= render 'form', person: @person %>

app/views/people/show.html.erb
<p id="notice"><%# notice %></p>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <%= render 'person_data' %>

      <!-- Second part of informations -->
      <% if @person.pakua_student? %>
        <div class="col-md-3">
          <!-- plan -->
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <h3 class="profile-username text-center">Plano</h3>
              <p class="text-muted text-center"><b><%= @person.student_plans.blank? ? "Nenhum plano definido" : @person.student_plans.last.current_tuition_fee.weekly_class_text %>
                <br>
                <%= @person.student_plans.blank? ? "" : @person.student_plans.last.current_discount.kind_of_plan.humanize.capitalize %></b></p>
              </p>

              <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                  <b>Dia de Vencimento</b> <a class="float-right"><%= @person.student_plans.blank? ? '-' : @person.student_plans.last.due_day %></a>
                </li>
                <li class="list-group-item">
                  <b>Aluga material?</b> <a class="float-right"><%= @person.student_plans.blank? ? '-' : logic_to_br(@person.student_plans.last.rent_inclusion) %></a>
                </li>
                <li class="list-group-item">
                  <b>Desconto</b> <a class="float-right"><%= @person.student_plans.last.blank? ? '-' : to_percent(@person.student_plans.last.current_discount.discount_percentage) %></a>
                </li>
                <li class="list-group-item">
                  <b>Valor da Mensalidade</b><a class="float-right"><%= @person.student_plans.blank? ? '-' : to_money(@person.student_plans.last.monthly_fee) %></a>
                </li>
              </ul>
              <% if @person.student_plans.blank? %>
                <%= link_to "Criar Plano do  #{pakua_title(@person).capitalize}", new_student_plan_path(@person), class: 'btn btn-primary btn-block' %>
              <% else %>
                <%= link_to "Editar Plano do #{pakua_title(@person).capitalize}", edit_student_plan_path(@person), class: 'btn btn-primary btn-block' %>
              <% end %>

              <%# link_to 'Editar', edit_person_path(@person), class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </div>
      <% end %>

      <%= render 'belts_information' %>
    </div>
    <div class="row">
      <% if @person.pakua_student? && !@person.student_plans.blank? %>
        <%= render 'payments' %>
        <%= render 'months_payment' %>
      <% end%>
      <% if @person.pakua_instructor? && !@any_pakua_class.blank? && @person.can_be_instructor? %>
        <%# render 'instructor_classes' %>
        <%# render 'months_payment' %>
      <% end %>
    </div>
  </div>
</section>