config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'member/sessions'
  }
  
  authenticated :member do

    resources :class_instructors
    root 'dashboard#index'

    get '/example', to: 'dashboard#example', as: 'dashboard_example'

    get '/planos_dos_alunos', to: 'student_plans#index', as: :student_plans
    post '/planos_dos_alunos', to: 'student_plans#create'
    scope 'aluno/:person_id/plano' do
      get '/novo', to: 'student_plans#new', as: :new_student_plan
      get '/editar', to: 'student_plans#edit', as: :edit_student_plan
      get '/', to: 'student_plans#show', as: :student_plan
      patch '/', to: 'student_plans#update'
      put '/', to: 'student_plans#update'
      delete '/', to: 'student_plans#destroy'
    end

    get '/faixas', to: 'belts#index', as: :belts
    post '/faixas', to: 'belts#create'
    scope 'aluno/:person_id/faixa' do
      get '/nova', to: 'belts#new', as: :new_belt
      get ':id/editar', to: 'belts#edit', as: :edit_belt
      get '/', to: 'belts#show', as: :belt
      get '/:id/mudar_faixa', to: 'belts#change_belt', as: :change_belt
    end

    scope 'aluno/:id/faixa' do
      patch '/', to: 'belts#update'
      put '/', to: 'belts#update'
      delete '/', to: 'belts#destroy'
    end

    scope 'financeiro' do
      get '/', to: 'dashboard#financial_index', as: :financial_index
      post '/novo_pagamento/:id/', to: 'payments#new_student_payment', as: 'new_student_payment'
      post '/receber_pagamento/:id/', to: 'payments#recive_payment', as: 'recive_payment'
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :tuition_fees, path: 'mensalidades'
        resources :rents, path: 'alugueis'
        resources :discounts, path: 'pacotes'
        resources :payments, path: 'pagamentos'
      end
    end

    scope 'administrativo' do
      get '/', to: 'dashboard#administrative_index', as: :administrative_index
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :pakua_classes, path: 'aulas'
      end
    end

    scope(path_names: { new: 'novo', edit: 'editar' }) do
      resources :people, path: 'membros'
    end

    get 'instrutores', to: 'instructors#index'
    get 'instrutores/novo', to: 'instructors#new'
    get 'instrutores/:id', to: 'instructors#show'
    get 'instrutores/:id/editar', to: 'instructors#edit'
    get 'instrutores', to: 'instructors#create'
    get 'instrutores/:id', to: 'instructors#update'
    get 'instrutores/:id', to: 'instructors#destroy'
    get 'alunos', to: 'students#index'
    get 'alunos/novo', to: 'students#new'
    get 'alunos/:id', to: 'students#show'
    get 'alunos/:id/editar', to: 'students#edit'
    get 'alunos', to: 'students#create'
    get 'alunos/:id', to: 'students#update'
    get 'alunos/:id', to: 'students#destroy'
    get 'membros/:id/informacao', to: 'people#edit_information', as: 'edit_information'
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

  unauthenticated :member do
    get '/inscricao', to: 'people#new_student_form', as: 'new_student_form'
    post '/membros', to: 'people#create', as: 'create_new_student'
    get '/boas_vindas', to: 'dashboard#welcome', as: 'welcome'
    get '/cadastro_existente', to: 'dashboard#welcome_back', as: 'welcome_back'
  end

  authenticate :member do
    get '/', to: 'dashboard#index', as: 'not_logged_root'
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  validates :discount_percentage, :starts_at, :kind_of_plan, presence: true

  enum kind_of_plan: {
    Mensal: 1,
    Trimestral: 3,
    Semestral: 6,
    Anual: 12
  }
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: %i[ show edit update destroy ]

  # GET /discounts or /discounts.json
  def index
    current_discounts
    @discounts = Discount.all - @current_discounts
  end

  # GET /discounts/1 or /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts or /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to discounts_path, notice: "Discount was successfully created." }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1 or /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discounts_path, notice: "Discount was successfully updated." }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1 or /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: "Discount was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discount_params
      params.require(:discount).permit(:discount_percentage, :starts_at, :kind_of_plan)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.erb
<section class="content">
  <div class="container-fluid">
    <%= form_with(model: discount, local: true) do |form| %>
      <% if discount.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

          <ul>
            <% discount.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Desconto</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <h4><%= form.label :kind_of_plan, 'Tipo de Desconto' %></h4>
                <%= form.select(:kind_of_plan, options_for_select(Discount.kind_of_plans.map {|k,v| [k.humanize.capitalize, Discount.kind_of_plans.key(v)] }), {}, class: "form-control rounded-0" )  %>
              </div>

              <div class="form-group">
                <h4 class="mb-0"><%= form.label :discount_percentage, 'Porcentagem de Desconto', class: "mb-0" %></h4>
                <%= form.text_field :discount_percentage, class: "form-control form-control-border" %>
              </div>

              <div class="form-group">
                <h4><%= form.label :starts_at, 'Início de vigência' %></h4>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                  </div>
                  <input type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask="" id="discount_starts_at" name="discount[starts_at]" value="<%= @discount.starts_at.nil? ? date_to_string(Date.today) : date_to_string(@discount.starts_at) %>">
                </div>
                <!-- /.input group -->
              </div>

              <div class="actions">
                <%= form.submit 'Salvar', class: 'btn btn-primary' %>
                <%= link_to 'Voltar para Administrativo', administrative_index_path, class: 'btn btn-secondary' %>
                <%= link_to 'Voltar para Pacotes', discounts_path, class: 'btn btn-secondary' %>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/discounts/edit.html.erb
<%= render 'form', discount: @discount %>

app/views/discounts/index.html.erb
<%= sanitize page_title_with_button('Pacotes', false) %>
<p id="notice"><%= notice %></p>

<section class="content">
  <%= generate_index_table({table_name: "Pacotes Vigentes", model: Discount, objects: @current_discounts, show_attributes: ['kind_of_plan', 'discount_percentage'], translated_names: ['Desconto', 'Pacote'], prefix_and_suffix: {'discount_percentage' => {pref: '', suff: '%'}}, new_label: 'Novo Desconto', crud_paths: true}).html_safe %>
  <br><br>
  <%= generate_index_table({table_name: "Pacotes Anteriores", model: Discount, objects: @discounts, show_attributes: ['kind_of_plan', 'discount_percentage'], translated_names: ['Desconto', 'Pacote'], prefix_and_suffix: {'discount_percentage' => {pref: '', suff: '%'}}, new_label: 'Novo Desconto', crud_paths: true}).html_safe %>
</section>

app/views/discounts/new.html.erb
<%= render 'form', discount: @discount %>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount percentage:</strong>
  <%= @discount.discount_percentage %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @discount.starts_at %>
</p>

<p>
  <strong>Kind of plan:</strong>
  <%= @discount.kind_of_plan %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>