config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'member/sessions'
  }
  
  authenticated :member do

    resources :class_instructors
    root 'dashboard#index'

    get '/example', to: 'dashboard#example', as: 'dashboard_example'

    get '/planos_dos_alunos', to: 'student_plans#index', as: :student_plans
    post '/planos_dos_alunos', to: 'student_plans#create'
    scope 'aluno/:person_id/plano' do
      get '/novo', to: 'student_plans#new', as: :new_student_plan
      get '/editar', to: 'student_plans#edit', as: :edit_student_plan
      get '/', to: 'student_plans#show', as: :student_plan
      patch '/', to: 'student_plans#update'
      put '/', to: 'student_plans#update'
      delete '/', to: 'student_plans#destroy'
    end

    get '/faixas', to: 'belts#index', as: :belts
    post '/faixas', to: 'belts#create'
    scope 'aluno/:person_id/faixa' do
      get '/nova', to: 'belts#new', as: :new_belt
      get ':id/editar', to: 'belts#edit', as: :edit_belt
      get '/', to: 'belts#show', as: :belt
      get '/:id/mudar_faixa', to: 'belts#change_belt', as: :change_belt
    end

    scope 'aluno/:id/faixa' do
      patch '/', to: 'belts#update'
      put '/', to: 'belts#update'
      delete '/', to: 'belts#destroy'
    end

    scope 'financeiro' do
      get '/', to: 'dashboard#financial_index', as: :financial_index
      post '/novo_pagamento/:id/', to: 'payments#new_student_payment', as: 'new_student_payment'
      post '/receber_pagamento/:id/', to: 'payments#recive_payment', as: 'recive_payment'
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :tuition_fees, path: 'mensalidades'
        resources :rents, path: 'alugueis'
        resources :discounts, path: 'pacotes'
        resources :payments, path: 'pagamentos'
      end
    end

    scope 'administrativo' do
      get '/', to: 'dashboard#administrative_index', as: :administrative_index
      scope(path_names: { new: 'novo', edit: 'editar' }) do 
        resources :pakua_classes, path: 'aulas'
      end
    end

    scope(path_names: { new: 'novo', edit: 'editar' }) do
      resources :people, path: 'membros'
    end

    get 'instrutores', to: 'instructors#index'
    get 'instrutores/novo', to: 'instructors#new'
    get 'instrutores/:id', to: 'instructors#show'
    get 'instrutores/:id/editar', to: 'instructors#edit'
    get 'instrutores', to: 'instructors#create'
    get 'instrutores/:id', to: 'instructors#update'
    get 'instrutores/:id', to: 'instructors#destroy'
    get 'alunos', to: 'students#index'
    get 'alunos/novo', to: 'students#new'
    get 'alunos/:id', to: 'students#show'
    get 'alunos/:id/editar', to: 'students#edit'
    get 'alunos', to: 'students#create'
    get 'alunos/:id', to: 'students#update'
    get 'alunos/:id', to: 'students#destroy'
    get 'membros/:id/informacao', to: 'people#edit_information', as: 'edit_information'
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

  unauthenticated :member do
    get '/inscricao', to: 'people#new_student_form', as: 'new_student_form'
    post '/membros', to: 'people#create', as: 'create_new_student'
    get '/boas_vindas', to: 'dashboard#welcome', as: 'welcome'
    get '/cadastro_existente', to: 'dashboard#welcome_back', as: 'welcome_back'
  end

  authenticate :member do
    get '/', to: 'dashboard#index', as: 'not_logged_root'
  end
end

app/models/student_plan.rb
class StudentPlan < ApplicationRecord
  belongs_to :person
  has_many :payments

  validates :due_day, :weekly_classes, :rent_inclusion, :kind_of_plan, presence: true

  def monthly_fee
    current_tuition_fee.fee + rent_cost
  end

  def percentage
    current_discount.discount_percentage
  end

  def current_tuition_fee
    TuitionFee.where(weekly_classes: weekly_classes).order(validity: 'DESC').first
  end

  def current_discount
    Discount.where(kind_of_plan: kind_of_plan).order(starts_at: 'DESC').first
  end

  def final_tuition_fee
    ((100.0 - percentage)/100) * monthly_fee
  end

  def weekly_classes_description
    weekly_classes.zero? ? 'Plano Livre' : "Plano de #{weekly_classes} aulas semanais"
  end

  def due_day_description
    "Dia #{due_day} ou final do mês" if due_day >= 28
    "Dia #{due_day}" if due_day < 28
  end

  def rent_cost
    self.rent_inclusion == 'true' ? Rent.last.rental_amount : 0 
  end
end

app/controllers/student_plans_controller.rb
class StudentPlansController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :set_student_plan, only: %i[show edit update destroy]
  before_action :block_if_plan_is_nil, except: %i[index new create]
  before_action :form_data, only: %i[new edit]

  # GET /student_plans or /student_plans.json
  def index
    @student_plans = StudentPlan.all
  end

  # GET /student_plans/1 or /student_plans/1.json
  def show
  end

  # GET /student_plans/new
  def new
    @student_plan = StudentPlan.new
  end

  # GET /student_plans/1/edit
  def edit
  end

  # POST /student_plans or /student_plans.json
  def create
    @student_plan = StudentPlan.new(student_plan_params)

    respond_to do |format|
      if @student_plan.save
        format.html { redirect_to person_path(@student_plan.person), notice: "Student plan was successfully created." }
        format.json { render :show, status: :created, location: @student_plan }
      else
        form_data
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_plans/1 or /student_plans/1.json
  def update
    respond_to do |format|
      if @student_plan.update(student_plan_params)
        format.html { redirect_to person_path(@student_plan.person), notice: "Student plan was successfully updated." }
        format.json { render :show, status: :ok, location: @student_plan }
      else
        form_data
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_plans/1 or /student_plans/1.json
  def destroy
    @student_plan.destroy
    respond_to do |format|
      format.html { redirect_to student_plans_url, notice: "Student plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private

  def set_person
    @person = Person.find(params[:person_id])
  end

  def set_student_plan
    @student_plan = @person.student_plans.order(id: 'DESC').first
  end

  def block_if_plan_is_nil
    if @student_plan.nil?
      msg = ''
      if @person.pakua_student?
        msg = 'Membro não possui plano'
      else
        msg = 'Apenas alunos possuem plano'
      end
      retirect_to people_path(@student_plans.people_id), notice: msg
    end
  end

  # Only allow a list of trusted parameters through.
  def student_plan_params
    params.require(:student_plan).permit(:person_id, :weekly_classes, :kind_of_plan, :rent_inclusion, :due_day)
  end

  def form_data
    if !@student_plan.nil?
      @person_id = !@student_plan.person.nil? ? @student_plan.person.id : params[:person_id]
    else
      @person_id = params[:person_id]
    end
    @view_action = %w[new create].include?(action_name) ? 'Novo Plano' : 'Editar Plano' 
    @discounts = Discount.kind_of_plans
    @weekly_classes = {}
    TuitionFee.all.select(:weekly_classes).each do |wc|
      if wc.weekly_classes.zero?
        @weekly_classes['Plano Livre'] = 0
      elsif wc.weekly_classes == 1
        @weekly_classes[(wc.weekly_classes.to_s + ' ' + 'aula'.pluralize(wc.weekly_classes) + ' ' + 'semanal'.pluralize(wc.weekly_classes)).to_sym] = wc.weekly_classes
      else
        @weekly_classes["#{wc.weekly_classes} aulas semanais"] = wc.weekly_classes
      end
    end
    @weekly_classes
  end
end

app/helpers/student_plans_helper.rb
module StudentPlansHelper
end

app/views/student_plans/_form.html.erb
<% if %w[new create].include? action_name %>
  <%= form_with(model: student_plan, local: true) do |form| %>
    <% if student_plan.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student_plan.errors.count, "error") %> prohibited this student_plan from being saved:</h2>

        <ul>
          <% student_plan.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-6">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"><%= @view_action %></h3>
        </div>
        <!-- /.card-header -->
        <%= form.hidden_field :person_id, value: @person_id %>

        <div class="card-body">
          <div class="form-group">
            <h4 class="mb-0"><%= form.label :due_day, 'Dia de Vencimento', class: "mb-0" %></h4>
            <%= form.number_field(:due_day, class: "form-control rounded-0", min: 1, max: 28 )  %>
          </div>
          
          <div class="form-group">
            <h4 class="mb-0"><%= form.label :rent_inclusion, 'Aluga Material?', class: "mb-0" %></h4>
            <%= form.select(:rent_inclusion, options_for_select([['Sim', true], ['Não', false]], @student_plan.rent_inclusion ? "true" : "false"), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="form-group">
            <h4 class="mb-0"><%= form.label :weekly_classes, 'Aulas Semanais' %></h4>
            <%= form.select(:weekly_classes, options_for_select(@weekly_classes.map { |k, v| [k.to_s.humanize, v]}), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="form-group">
            <h4 class="mb-0"><%= form.label :kind_of_plan, 'Tipo de Plano' %></h4>
            <%= form.select(:kind_of_plan, options_for_select(@discounts.map { |k, v| [k.to_s.humanize, v]}), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="actions">
            <%= form.submit 'Salvar', class: 'btn btn-primary' %>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  <% end %>

<% else %>
  <%= form_for :student_plan, url: url_for(controller: 'student_plans', action: 'update'), method: :put do |form| %>
    <% if student_plan.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student_plan.errors.count, "error") %> prohibited this student_plan from being saved:</h2>

        <ul>
          <% student_plan.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-6">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"><%= @view_action %></h3>
        </div>
        <!-- /.card-header -->
        <%= form.hidden_field :person_id, value: @person_id %>

        <div class="card-body">
          <div class="form-group">
            <h4 class="mb-0"><%= form.label :due_day, 'Dia de Vencimento', class: "mb-0" %></h4>
            <%= form.number_field(:due_day, class: "form-control rounded-0", min: 1, max: 28 )  %>
          </div>
          
          <div class="form-group">
            <h4 class="mb-0"><%= form.label :rent_inclusion, 'Aluga Material?', class: "mb-0" %></h4>
            <%= form.select(:rent_inclusion, options_for_select([['Sim', 'true'], ['Não', 'false']], selected: @student_plan.rent_inclusion), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="form-group">
            <h4 class="mb-0"><%= form.label :weekly_classes, 'Aulas Semanais' %></h4>
            <%= form.select(:weekly_classes, options_for_select(@weekly_classes.map { |k, v| [k.to_s.humanize, v]}, selected: @student_plan.weekly_classes), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="form-group">
            <h4 class="mb-0"><%= form.label :kind_of_plan, 'Tipo de Plano' %></h4>
            <%= form.select(:kind_of_plan, options_for_select(@discounts.map { |k, v| [k.to_s.humanize, v]}, selected: @student_plan.kind_of_plan), {}, class: "form-control rounded-0" )  %>
          </div>

          <div class="actions">
            <%= form.submit 'Salvar', class: 'btn btn-primary' %>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  <% end %>
<%end%>
  

app/views/student_plans/edit.html.erb
<%= render 'form', student_plan: @student_plan %>

<%= link_to 'Show', @student_plan %> |
<%= link_to 'Back', student_plans_path %>

app/views/student_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Plans</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Aulas semanais</th>
      <th>Desconto</th>
      <th>Aluga Equipamento</th>
      <th>Due day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_plans.each do |student_plan| %>
      <tr>
        <td><%= student_plan.person_id %></td>
        <td><%= student_plan.weekly_classes %></td>
        <td><%= student_plan.kind_of_plan %></td>
        <td><%= student_plan.rent_inclusion %></td>
        <td><%= student_plan.due_day %></td>
        <td><%= link_to 'Show', student_plan %></td>
        <td><%= link_to 'Edit', edit_student_plan_path(student_plan) %></td>
        <td><%= link_to 'Destroy', student_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Student Plan', new_student_plan_path %>

app/views/student_plans/new.html.erb
<%= render 'form', student_plan: @student_plan %>

<%= link_to 'Back', student_plans_path %>

app/views/student_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>People:</strong>
  <%= @student_plan.people_id %>
</p>

<p>
  <strong>Tuition fee:</strong>
  <%= @student_plan.tuition_fee_id %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @student_plan.discount_id %>
</p>

<p>
  <strong>Rent inclusion:</strong>
  <%= @student_plan.rent_inclusion %>
</p>

<p>
  <strong>Due day:</strong>
  <%= @student_plan.due_day %>
</p>

<%= link_to 'Edit', edit_student_plan_path(@student_plan) %> |
<%= link_to 'Back', student_plans_path %>